name: CI

on: [push, pull_request]

env:
  DOTNET_SDK_VERSION: '6.0.100-preview.5.21302.13'
  GMOD_DOT_NET_VERSION: '0.7.0-beta.2.46713465.main'

jobs:
  linux-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Download Steam and install garrysmod
        run: |
             wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
             tar -xvzf steamcmd_linux.tar.gz
             rm -rfv steamcmd_linux.tar.gz
             ./steamcmd.sh +login anonymous +force_install_dir gmod "+app_update 4020 -beta x86-64 validate" +quit

      - name: Publish Test
        run: dotnet publish ./Tests/Tests.csproj -c Release -o ./gmod/garrysmod/lua/bin/Modules/Tests

      - name: Download GmodDotNet
        working-directory: ./gmod/garrysmod/lua/bin/
        run: |
             wget https://gleb-krasilich.fra1.digitaloceanspaces.com/GmodNETStorage/storage/gmod-dot-net-linux.${{ env.GMOD_DOT_NET_VERSION }}.tar.gz
             tar -xvf gmod-dot-net-linux.${{ env.GMOD_DOT_NET_VERSION }}.tar.gz
             rm -rfv gmod-dot-net-linux.${{ env.GMOD_DOT_NET_VERSION }}.tar.gz

      - name: Copy Lua file
        run: cp tests-run.lua ./gmod/garrysmod/lua/autorun

      - name: Run Garry's Mod
        working-directory: ./gmod/
        run: ./srcds_run_x64 -game garrysmod -systemtest -condebug +sv_hibernate_think 1
        continue-on-error: true
        timeout-minutes: 1

      - name: Print console log
        working-directory: ./gmod/garrysmod/
        run: cat console.log
      
      - name: Check tests success
        working-directory: ./gmod/
        run: cat test-success.txt